# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 18:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='content goes here'),
        ),
    ]
